# docker-compose.dev.yml
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: gasosa
      MYSQL_USER: addiz
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:

