services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: gasosa
      MYSQL_USER: addiz
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backend_net

  tomcat:
    build: .
    container_name: tomcat_app
    ports:
      - "8288:8288"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: gasosa
      DB_USER: addiz
      DB_PASS: senha
    networks:
      - backend_net

volumes:
  mysqldata:

networks:
  backend_net:
